import React, { useEffect, useState } from 'react';
import { Clipboard, Router, ShieldCheck, Wrench } from 'lucide-react';
import { apiClient } from '../services/api';
import { Assessment, Device } from '../types';

export const ConfigAdvisorPage: React.FC = () => {
  const [audit, setAudit] = useState<Assessment | null>(null); const [deviceId, setDeviceId] = useState(''); const [copied, setCopied] = useState(false);
  useEffect(() => { apiClient.listAssessments().then(items => items[0] && apiClient.getAssessment(items[0].id).then(data => {setAudit(data); setDeviceId(data.devices[0]?.id || '');})).catch(() => undefined); }, []);
  const device = audit?.devices.find(d => d.id === deviceId); const findings = audit?.findings.filter(f => f.device_id === deviceId) || [];
  const config = findings.map(f => f.remediation_script).filter(Boolean).join('\n\n') || '! No generated commands are required for this device baseline.';
  const copy = async () => { await navigator.clipboard.writeText(config); setCopied(true); setTimeout(() => setCopied(false), 1600); };
  return <div className="space-y-6 pb-16"><div><p className="text-cyan-400 text-xs font-semibold uppercase tracking-widest">Evidence-based hardening</p><h1 className="text-2xl font-bold text-white mt-1">Router & Switch Config Advisor</h1><p className="text-sm text-slate-400 mt-1">Commands are generated from the findings in your latest audit. Review and test them before deploying.</p></div>{!audit ? <div className="p-10 rounded-2xl border border-dashed border-slate-700 text-center text-slate-400">Run an audit first to get vendor-specific configuration guidance.</div> : <><div className="flex gap-3 items-center"><Router className="w-5 h-5 text-cyan-400"/><select value={deviceId} onChange={e => setDeviceId(e.target.value)} className="bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-slate-100 text-sm">{audit.devices.map(d => <option value={d.id} key={d.id}>{d.hostname || d.filename} — {d.vendor}</option>)}</select></div><div className="grid lg:grid-cols-3 gap-5"><div className="lg:col-span-2 p-5 rounded-2xl bg-[#0B0F19] border border-slate-800"><div className="flex justify-between items-start gap-4 mb-4"><div><h2 className="text-white font-semibold">Recommended {device?.vendor} hardening commands</h2><p className="text-xs text-slate-400 mt-1">Derived from {findings.length} open finding(s); sensitive evidence remains masked.</p></div><button onClick={copy} className="shrink-0 px-3 py-2 rounded-lg bg-cyan-500 text-slate-950 text-xs font-semibold"><Clipboard className="w-3 h-3 inline mr-1"/>{copied ? 'Copied' : 'Copy'}</button></div><pre className="whitespace-pre-wrap text-xs leading-6 bg-slate-950 border border-slate-800 p-4 rounded-xl text-emerald-300 overflow-x-auto">{config}</pre></div><aside className="p-5 rounded-2xl bg-[#0B0F19] border border-slate-800"><ShieldCheck className="w-6 h-6 text-cyan-400 mb-3"/><h2 className="text-white font-semibold">Safe rollout</h2><ol className="text-xs text-slate-400 leading-6 mt-2 list-decimal pl-4"><li>Back up the current startup configuration.</li><li>Test in a maintenance window or lab.</li><li>Use a console path to avoid lockout.</li><li>Validate management access and monitoring.</li><li>Re-upload the new config to verify the score.</li></ol></aside></div></>}</div>;
};
