import React, { useEffect, useState } from 'react';
import { FileText, Download, ShieldCheck, Clock, ArrowRight } from 'lucide-react';
import { apiClient } from '../services/api';
import { useNavigate } from 'react-router-dom';
import { useNotifications } from '../context/NotificationContext';

export const ReportsPage: React.FC = () => {
  const [reports, setReports] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [downloading, setDownloading] = useState<string | null>(null);
  const navigate = useNavigate(); const { addNotification } = useNotifications();
  useEffect(() => { apiClient.listAssessments().then(setReports).catch(() => addNotification('Unable to load reports', 'Please check that the local backend is running.', 'error')).finally(() => setLoading(false)); }, []);
  const download = async (report: any) => { setDownloading(report.id); try { await apiClient.downloadPdfReport(report.id); } catch (e) { addNotification('Report download failed', e instanceof Error ? e.message : 'Try again shortly.', 'error'); } finally { setDownloading(null); } };
  return <div className="space-y-6 pb-16"><div className="flex flex-col sm:flex-row gap-4 sm:items-end sm:justify-between"><div><p className="text-cyan-400 text-xs font-semibold uppercase tracking-widest">Private report library</p><h1 className="text-2xl font-bold text-white mt-1">Audit Reports</h1><p className="text-sm text-slate-400 mt-1">Only audits created under your signed-in local account appear here.</p></div><button onClick={() => navigate('/audit')} className="px-4 py-2 rounded-xl bg-cyan-500 text-slate-950 text-sm font-semibold">Run a new audit</button></div>{loading ? <p className="text-slate-400">Loading your reports…</p> : reports.length === 0 ? <div className="p-10 rounded-2xl border border-dashed border-slate-700 text-center"><ShieldCheck className="w-10 h-10 text-cyan-400 mx-auto mb-3"/><p className="text-white font-semibold">No reports yet</p><p className="text-slate-400 text-sm mt-1">Upload a configuration to create your first encrypted local audit record.</p></div> : <div className="grid gap-3">{reports.map(report => <div key={report.id} className="p-5 rounded-2xl bg-[#0B0F19] border border-slate-800 flex flex-col sm:flex-row gap-4 sm:items-center"><FileText className="w-7 h-7 text-cyan-400 shrink-0"/><div className="flex-1"><p className="text-white font-semibold">{report.name}</p><p className="text-xs text-slate-400 mt-1 flex gap-2 items-center"><Clock className="w-3 h-3"/>{new Date(report.created_at).toLocaleString()} · {report.total_devices} device(s) · score {Math.round(report.overall_score)}/100</p><p className="text-xs text-rose-300 mt-2">{report.critical_count} critical · {report.high_count} high findings</p></div><div className="flex gap-2"><button onClick={() => navigate(`/findings?audit=${report.id}`)} className="px-3 py-2 rounded-lg border border-slate-700 text-slate-200 text-xs">View details <ArrowRight className="w-3 h-3 inline"/></button><button onClick={() => download(report)} className="px-3 py-2 rounded-lg bg-cyan-500 text-slate-950 font-semibold text-xs"><Download className="w-3 h-3 inline mr-1"/>{downloading === report.id ? 'Preparing' : 'PDF'}</button></div></div>)}</div>}</div>;
};
