# ==============================================================================
# NetGuard AI Synthetic Lab Configuration (Hardened FortiGate Firewall)
# WARNING: FOR AUDIT SIMULATION ONLY — NOT FOR PRODUCTION USE
# ==============================================================================
#config-version=FGT100F-7.2.4:opmode=0
config system global
    set hostname "FortiGate-Lab-FW-Secure"
    set admintimeout 10
    set pre_login_banner enable
    set admin-sport 8443
    set admin-ssh-port 2222
end

config system interface
    edit "port1"
        set mode static
        set ip 192.0.2.254 255.255.255.0
        set allowaccess ping
    next
    edit "mgmt"
        set mode static
        set ip 10.10.100.1 255.255.255.0
        set allowaccess https ssh
    next
end

config system admin
    edit "secops_admin"
        set trusthost1 10.10.100.0 255.255.255.0
        set password ENC HardenedEncryptedPassHash
        set accprofile "super_admin"
    next
end

config log syslogd setting
    set status enable
    set server "10.10.10.50"
    set mode udp
    set port 514
end

config system ntp
    set ntpsync enable
    config ntpserver
        edit 1
            set server "10.10.10.10"
        next
    end
end

config system snmp user
    edit "sec_snmp3"
        set security-level auth-priv
        set auth-proto sha256
        set auth-pwd ENC ShaAuthEncrypted
        set priv-proto aes
        set priv-pwd ENC AesPrivEncrypted
    next
end

config firewall policy
    edit 1
        set name "DMZ_Inbound_Strict"
        set srcintf "port1"
        set dstintf "mgmt"
        set srcaddr "SOC_Subnet"
        set dstaddr "Bastion_Host"
        set action accept
        set schedule "always"
        set service "HTTPS" "SSH"
        set logtraffic all
    next
end
