#config-version=FGT100F-7.2.4-FW-build1396-230308:opmode=0:vdom=0
# Fortinet FortiGate Firewall Configuration — Hardened Baseline
# NetGuard AI Sample Audit File

config system global
    set hostname "FortiGate-Core-FW02"
    set admintimeout 10
    set pre_login_banner enable
    set admin-password-hash pbkdf2
end

config system interface
    edit "port1"
        set vdom "root"
        set ip 198.51.100.2 255.255.255.0
        set allowaccess ping
        set type physical
    next
    edit "mgmt1"
        set vdom "root"
        set ip 10.10.100.1 255.255.255.0
        set allowaccess https ssh
        set type physical
    next
end

config system admin
    edit "secops_admin"
        set password ENC AK1b3x9...StrongEncryptedHash
        set trusthost1 10.10.100.0 255.255.255.0
        set accprofile "super_admin"
        set vdom "root"
    next
end

config system ntp
    set ntpsync enable
    set type custom
    set syncinterval 60
    config ntpserver
        edit 1
            set server "10.10.10.10"
            set authentication enable
            set key-type sha1
            set key-id 1
            set key ENC StrongNtpKey123
        next
    end
end

config log syslogd setting
    set status enable
    set server "10.10.10.50"
    set mode udp
    set port 514
    set facility local7
end

config system snmp user
    edit "snmpv3_collector"
        set status enable
        set trap-status enable
        set security-level auth-priv
        set auth-proto sha256
        set auth-pwd ENC StrongAuthPwd456
        set priv-proto aes256
        set priv-pwd ENC StrongPrivPwd789
    next
end

config vpn ipsec phase1-interface
    edit "SECURE_VPN_IPSEC"
        set interface "port1"
        set peertype any
        set proposal aes256-sha256 aes128-sha256
        set dhgrp 14 19
        set remote-gw 203.0.113.80
        set psksecret ENC StrongPskKey444
    next
end

config firewall policy
    edit 10
        set name "Allow_DMZ_HTTPS_Inbound"
        set srcintf "port1"
        set dstintf "mgmt1"
        set srcaddr "AUTHORIZED_REMOTE_NETS"
        set dstaddr "DMZ_VIP_HTTPS"
        set action accept
        set schedule "always"
        set service "HTTPS"
        set logtraffic all
    next
end
